Month 8/step 2
Kartinkartin/react-burger pull request #3
Opened 2022-09-17 09:29 UTC by Kartinkartin

Я прошу прощения, Михаил. Труд сделал из обезьяны человека, я видимо прошла обратную эволюцию. -.-

2022-09-17 13:35 UTC, randomroot requested changes
**Здравствуйте!**

Не волнуйтесь, каждому человеку свойственно ошибаться и в процессе обучения это даже полезно, чтобы закрепить ваши знания и навыки 😸 

**У вас хорошая работа**, с подключением и использованием Redux вы успешно справились, дополнительно хотел бы отметить **интересную и универсальную** реализацию автоматического переключения табов, в зависимости от позиции скролла в списке ингредиентов, а также **оптимальный** подход по обновления значений счетчика у ингредиентов в хранилище.

Однако, для успешной сдачи работы вам необходимо внимательно ознакомиться и исправить выявленные недочеты, а также обратить внимание на предложенные улучшения для повышения качества и производительности
вашего кода. Кроме уазанных в ревью комментариев есть несколько общих моментов, которые также важно изучить и принять к сведению:

**Можно улучшить**

- по верстке:

1) В хедере элементы меню состоящие из двух слов расположены в двух строках, согласно макету они расположены в одной;

2) На элементах с которыми можно производить взаимодействие лучше заменять тип курсора на руку, чтобы наглядно показать пользователю возможность что-нибудь с ним сделать :)

3) Между списком ингредиентов и нижней булкой отступ отличается от отступа с верхней булкой;

4) Отступы между ингредиентами в общем списке слева отличаются от тех, что указаны на макете;

5) Присутствует вертикальный скролл всего приложения, это может негативно сказываться на пользовательском опыте.

- по UX/JS:

1) При увеличении сложности проекта расположение экшенов и редьюсеров в рамках одного файла (каждого) может серьезно ухудшать читабельность кода и усложнять процессы их тестирования.

Рекомендуется разделить их по отдельным файлам, соответствующих тому или иному компоненту/сущности (что можно отразить в названии нового файла) и затем объединить, как у вас уже реализовано через `combineReducers`: 
это позволит разделить большой `store` на несколько маленьких, станет проще отслеживать их состояния и сбрасывать при необходимости, а также исключить случайные ре-рендеры за счет обновления только нужных частей, а не всего стора, на который могут среагировать все селекторы в компонентах;

2) При неудачном создании заказа по причине ошибки сервера/отсутствия сети и других причин, рекомендуется уведомить пользователя об этом, например в модальном окне или другим доступным методом по вашему выбору. В текущей реализации открытое окно с пустым значением ID заказа может вызвать непонимания
у пользователей, что случилось :)

3) Автоматическое переключение категории в зависимости от положения скроллбара у вас реализовано, попробуйте добавить еще возможность осуществлять переход к нужной категории по нажатию соответствующего таба ;)

4) В проекте присутствует описание контекстов, которые остались с предыдущего этапа, их можно безопасно удалить, т.к. они более не используются;

5) Обратите внимание на форматирование вашего кода, при необходимости используйте встроенные в вашу IDE возможности, чтобы удалить лишние пробелы и строки, исправить отступы и вложенность.

В качестве дополнительного совета, рекомендую вам в `package.json` фиксировать версии ваших библиотек (хорошее описание можно найти здесь: https://learn.microsoft.com/ru-ru/visualstudio/javascript/configure-packages-with-package-json?view=vs-2022),
это поможет избежать случайных ошибок по причине действий авторов некоторых библиотек, включающих в себя появление новых багов в них или нежелательного поведения в связи с которым проект может перестать работать полностью.

**Успешного вам рефакторинга и хороших выходных!** 🐈 

P.S. _Для улучшения настроения и хорошей продуктивности мотивирую вас этим прекрасным котиком:_

![image](https://64.media.tumblr.com/tumblr_lkjzi7qMsS1qhy6c9o1_400.gifv)

2022-09-17 13:35 UTC, randomroot commented on src/components/api/api.js
> +  const idList ={ "ingredients": orderList.map(item => item._id) }
🔴 **Нужно исправить:**

1) В итоговый заказ попадает только одно значение булки, хотя выбрано и рассчитана цена на две, следует добавить вторую;
2) Расположение булок в массиве заказа должно быть на первом и последнем месте, чтобы соблюсти очередность элементов в рамках бургера.

🟡 **Можно улучшить:**

1) В случаях когда ключом в объекте является единственное слово на латинице кавычки можно опустить;
2) В данном случае имеет смысл передавать в данную функцию именно массив ID-шников, а подготовительные операции для исполнения вызова API лучше вынести в рамках экшена, чтобы разделить логику подготовки данных и непосредственного исполнения запроса в утилитах;

2022-09-17 13:35 UTC, randomroot commented on src/components/api/api.js
> +    body:JSON.stringify(idList)
🟡 **Можно улучшить:**

_Форматирование:_ следует добавить пробел между ключом и значением на данной строке

2022-09-17 13:35 UTC, randomroot commented on src/components/app/app.jsx
> +        <Modal title=' ' onClose={closePopup} number={orderNum}>
🟡 **Можно улучшить:**

Если значение пропса может быть пустым, то рекомендуется в соответствующем компоненте указать его как необязательное и задать значение по умолчанию, чтобы в рамках остального кода его можно было не указывать :)

2022-09-17 13:35 UTC, randomroot commented on src/components/app/app.jsx
> +      { openingOrder &&
🟡 **Можно улучшить:**

Модальные окна в данном случае относятся не ко всему приложению в целом, а конкретно к конструктору заказа и списку ингредиентов, поэтому лучше переместить их в соответствующие компоненты и упростить логику `app.jsx`.

Данный файл, наравне с `index.js` является своеобразной точкой входа в ваше приложение, поэтому желательно их держать максимально простыми, за исключением глобальных взаимодействий/переменных.

Плюс, в случае переноса необходимость в пропсе `onClick` просто отпадает :)

2022-09-17 13:35 UTC, randomroot commented on src/components/app/app.jsx
> +  const orderNum = useSelector(store=>store.order.number).toString();
🟡 **Можно улучшить:**

Вызов функции `toString` следует перенести внутрь скобок, непосредственно над значением `number`

2022-09-17 13:35 UTC, randomroot commented on src/components/app/app.jsx
>    function closePopup(e) {
🟡 **Можно улучшить:**

Неиспользуемые параметры функций можно безопасно удалить из кода

2022-09-17 13:35 UTC, randomroot commented on src/components/app/app.jsx
> +    dispatch({
🟢 **Отлично:**

Сброс данных после успешного выполнения запроса - это отличная практика, так держать 👍

2022-09-17 13:35 UTC, randomroot commented on src/components/app/app.jsx
> +    dispatch({
🟡 **Можно улучшить:**

В названии функции допущена орфографическая ошибка в слове `Ingredients`

2022-09-17 13:35 UTC, randomroot commented on src/components/app/app.jsx
>          <div className={styles.main}>
🟡 **Можно улучшить:**

С точки зрения семантики данный элемент желательно заменить на `main` вместо `div`, так как именно в нём лежит основной контент приложения

2022-09-17 13:35 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +    const notBunsIngredients = ingredientsConstructor.filter(prod => prod.type != 'bun')
🔴 **Нужно исправить:**

Для сравнение значений переменных следует использовать строгое неравенство `!==`, т.к. могут возникуть нежелательные побочные эффекты, связанные с автоматической конвертации типов (см. https://learn.javascript.ru/comparison#strogoe-sravnenie)

2022-09-17 13:35 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +    const [droppedIndex, setdroppedIndex] = useState(false);
🔴 **Нужно исправить:**

Для именования функций следует придерживаться стиля `camelCase`, аналогично на строке ниже

🟡 **Можно улучшить:**

Значения переменных `droppedIndex` и `draggedIndex` - это числа, поэтому в начальном состоянии указание `boolean` переменной нарушает его типизацию, в данном случае лучше указать или пустое значение, например `null` или отрицательное -1, так как индекс не может быть отрицательным :)

2022-09-17 13:35 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +    const [bunEl, setBunEl] = useState({});
🟡 **Можно улучшить:**

В случаях, когда начальное состояние переменной считается пустым лучше использовать `null` или `undefined` и обеспечить в нужных местах соответствующие проверки на пустоту значения, чтобы случайно не обратиться к ключам пустого объекта

2022-09-17 13:35 UTC, randomroot commented on src/index.jsx
> +// declare global {
🔴 **Нужно исправить:**

Неиспользуемый код следует удалить из файла, чтобы поддерживать его читабельность. При необходимости его всегда можно будет восстановить через историю Git-а.

Аналогично ниже на 29 строке

2022-09-17 13:35 UTC, randomroot commented on src/components/api/api.js
> +export function checkRes(res) {
🟡 **Можно улучшить:**

Данную функцию можно оставить как внутреннюю без экспорта и вызывать её напрямую в методах данного файла, чтобы не импортировать её дополнительно в другие файлы

2022-09-17 13:35 UTC, randomroot commented on src/components/layer/layer.jsx
> +        <li className={styles.layer_element + " pb-4"} draggable ref={dragRef} onDrag={()=>handleDrag(index)} onDrop={(e)=>handleDrop(e, index)} style={ {opacity} }>
🟡 **Можно улучшить:**

В случае когда в компоненте много пропсов лучше из одной строки их перенести на несколько строк для улучшения читабельности кода;

2022-09-17 13:35 UTC, randomroot commented on src/components/layer/layer.jsx
> +   prod: PropTypes.object.isRequired
🔴 **Нужно исправить:**

Следует добавить и другие пропсы, которые передаются в данный файл, которые указаны на 7-ой строке данного файла

2022-09-17 13:35 UTC, randomroot commented on src/components/layer/layer.jsx
> +export function Layer(props) {
🟡 **Можно улучшить:**

Компоненты следует именовать исходя из их функционального предназначения. В данном случае понятие `Layer` довольно универсальное, однако судя по внутренностям компонента он предназначен только для конструктора, поэтому более подходящим по смыслу названием будет, например, `BurgerConstructorElement`

2022-09-17 13:35 UTC, randomroot commented on src/components/layer/layer.jsx
> +                handleClose={(e)=> {handleDelete(e, index)}}
🟡 **Можно улучшить:**

Фигурные скобки внутри стрелочной функции можно опустить, если подразумевается исполнение только одной строки кода, чтобы не создавать дополнительных замыканий

2022-09-17 13:35 UTC, randomroot commented on src/components/ingredient/ingredient.jsx
> +        type: 'item', /*card.type*/
🟡 **Можно улучшить:**

Для каждого типа перетаскиваемого элемента лучше указывать уникальное название, чтобы избежать случайных ошибок по причине перетаскивания их в другое окно, которое принимает такой же тип. Пример совпадение типов в вашем проекте: данный компонент и компонент `Layer`

2022-09-17 13:35 UTC, randomroot commented on src/services/reducers/index.js
> +const InitialItemsReducer = (state=initialState.ingredientsApi, action) => {
🔴 **Нужно исправить:**

Имена переменных следует именовать согласно подходу `camelCase`, исключение составляют только названия React компонентов

2022-09-17 13:35 UTC, randomroot commented on src/services/actions/index.js
> +        type: GET_API_ITEMS_REQUEST //модалка с ожиданием?
🔴 **Нужно исправить:**

_Форматирование:_ вложенные значения должны иметь отступ относительно родительского элемента, аналогично ниже по коду

2022-09-17 13:35 UTC, randomroot commented on src/services/actions/index.js
> +        .then(res => checkRes(res))
🟡 **Можно улучшить:**

Здесь можно напрямую передать `.then(checkRes)`, чтобы не создавать дополнительную стрелочную функцию. Это также применимо к любой другой передачи функции, если параметры вызываемой функции совпадают с ожидаемыми параметрами

2022-09-17 13:35 UTC, randomroot commented on src/components/burger-ingredients/burger-ingredients.jsx
> +    const HightlightTab = (e) => {
🔴 **Нужно исправить:**

Для именования функций следует придерживаться стиля camelCase

2022-09-17 13:35 UTC, randomroot commented on src/components/burger-ingredients/burger-ingredients.jsx
> +    const refs = [bunRef, mainRef, sauceRef];
🟡 **Можно улучшить:**

Данный массив у вас используется только в рамках функции `highlightTab`, поэтому его лучше переместить туда, ближе к коду, который непосредственно его использует, либо замемоизировать, с учетом того, что переменные входящие в его состав не будут изменяться в рамках компонента, а актуальное значение получаем через `current`

2022-09-17 13:35 UTC, randomroot commented on src/components/burger-ingredients/burger-ingredients.jsx
> +        const currentTabRef = refs[positions.indexOf(Math.min.apply(null, positions))];
🟢 **Отлично:**

У вас получился очень интересный подход по поиску необходимого элемента, который нужно выделить 👍 

🟡 **Можно улучшить:**

Кроме того, хотел бы обратить ваше внимание на библиотеку `react-intersection-observer`, которая позволит вам решить данную задачу без дополнительного кода с вашей стороны, связанного с расчетами. Т.к. использование сторонних библиотек не регламентировано в рамках задания, таким образом можно упростить ваш код, отдав решение части задач сторонним проверенным решениям, как часто происходит на реальных проектах :)

2022-09-17 13:35 UTC, randomroot commented on src/components/burger-ingredients/burger-ingredients.jsx
> +        setCurrent(currentSection === 'Булки' ? 'bun' :
🟡 **Можно улучшить:**

Привязка к текстовым значениям может сломаться, если в рамках проекта будет использоваться несколько языков. Поэтому лучше ориентироваться именно на собственный ключ, который вы, например, можете указать в соответствующем элементе (см. https://developer.mozilla.org/ru/docs/Learn/HTML/Howto/Use_data_attributes) и получить его значение также через реф.

2022-09-17 13:35 UTC, randomroot commented on src/components/burger-ingredients/burger-ingredients.jsx
> +function MenuCategory({cards, type, refer, onClick}) {
🟡 **Можно улучшить:**

React компоненты лучше разделять по отдельным файлам и папкам, чтобы упростить их тестирование, уменьшить количество кода в рамках одного файла и легче переиспользовать при необходимости :)

2022-09-17 13:35 UTC, randomroot commented on src/components/burger-ingredients/burger-ingredients.jsx
>          <div className={styles.category + " " + "pl-4 pr-4"}>
🟡 **Можно улучшить:**

Для соединения строк попробуйте использовать "шаблонные строки" (см. https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Template_literals)

2022-09-17 13:35 UTC, randomroot commented on src/services/reducers/index.js
> +            const currentBun = state.ingredientsConstructor.filter(item => item.type == 'bun')[0];
🔴 **Нужно исправить:**

Для сравнения значений элементов следует использовать строгое равенство, чтобы избежать побочных эффектов, связанных с преобразованиями типов (см. https://learn.javascript.ru/comparison#strogoe-sravnenie).

Аналогично ниже в рамках данного редьюсера

2022-09-17 13:35 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +    const [state, dispatchPrice] = useReducer(reducer, {price: 0});
🟢 **Отлично:**

Вам удалось успешно применить на практике использование хука `useReducer` 👍 

🟡 **Можно улучшить:**

Код можно упростить, если заменить использование данного хука на `useMemo` и рассчитывать стоимость заказа динамически на основе параметров из `ingredientsConstructor`, сведя его в одну небольшую функцию.

2022-09-17 13:35 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +            case ('sauce'):
🔴 **Нужно исправить:**

В данном случае код изменения цены дублирует код из случая `main`, поэтому его следует удалить, т.к. оператор `switch` позволяет на несколько `case` реагировать одинаково (см. первый пример https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Statements/switch#examples)

2022-09-17 13:35 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +            <>
🔴 **Нужно исправить:**

_Форматирование:_ дочерние элементы следует расположить с отступом относительно родительского элемента

2022-09-17 13:35 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +            { bunEl.name &&
🟡 **Можно улучшить:**

JSX элементы в таких выражениях рекомендуется оборачивать в круглые скобки для поддержания общего стиля кода

2022-09-17 13:35 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +                            <Layer prod={item} index={index} key={item._id + Math.random().toString(7).slice(2, 7)} handleDelete={handleDeleteItem} handleDrag={handleDrag} handleDrop={handleDrop}/>
🟡 **Можно улучшить:**

Рассмотрите возможности использования библиотеки `uuid` для генерации уникальных значений для вашего ключа

2022-09-17 13:35 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
>                      <CurrencyIcon />
🟡 **Можно улучшить:**

Значение пропса `type` у иконки является обязательным, следует его добавить

2022-09-17 13:35 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +        if(droppedIndex > draggedIndex) {
🟡 **Можно улучшить:**

Сортировку и удаление элемента лучше производить непосредственно в соответствующем редьюсере исходя из состояния стейта, чтобы избежать возможных ошибок из-за их рассинхронизации и разделить логику работы с данными, так как основным источником является именно стор, а не компонент

2022-09-17 13:35 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +        setdraggedIndex(false);
🔴 **Нужно исправить:**

Функция `setdraggedIndex` вызывается дважды, возможно произошла опечатка или ожидался вызов функции `setdroppedIndex`

2022-09-17 13:35 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
>          }
🟡 **Можно улучшить:**

Вложенные тернарные операторы усложняют код и ухудшают его читабельность, иногда лучше воспользоваться классической конструкцией `if`

2022-09-17 13:35 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +            type: 'increment',
🟡 **Можно улучшить:**

На самом деле в случае булки не происходит увеличение цены, она просто изменяется, поэтому значение типа может быть неправильно интерпретировано

2022-09-17 13:35 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +                <Button type="primary" size="large" onClick={onClick} disabled={!bunEl.name}>
🟢 **Отлично:**

Отключение кнопки в отсутствие нужных ингредиентов - это хорошая практика, которая позволит исключить лишние вызовы к API 👍

2022-09-17 13:35 UTC, randomroot commented on src/services/reducers/index.js
> +            return state
🟡 **Можно улучшить:**

Для экшенов загрузки можно добавить в  соответствующий стор переменную `loading`, обозначающую, что загрузка в процессе, на основе которой отображать лоадер или другое информационное сообщение о том, что нужно подождать

2022-09-17 13:35 UTC, randomroot commented on src/services/reducers/index.js
> +            return {...state}
🟡 **Можно улучшить:**

1) Ошибочный результат тоже можно положить в стор и отображать пользователю в чистом или человекопонятном формате, чтобы он понимал, что произошло не так.
2) Так как вы не изменяете `store` его можно вернуть обратно без создания дополнительной копии

2022-09-17 13:35 UTC, randomroot commented on src/services/reducers/index.js
> +    return state.ingredientsConstructor.map(item=>item._id).includes(action.item._id)
🔴 **Нужно исправить:**

Несмотря на то, что проверка выполняется верно, текущая реализация не является оптимальной, т.к. происходит 2 операции: 
1) Полный проход по массиву с созданием нового, в рамках которого происходит преобразование каждого элемента в `id`;
2) Полный проход по новому массиву в целях поиска нужного элемента.

Это приводит к увеличению расходов памяти (в худшем случае новый массив будет по размеру равен исходному) и ухудшению производительности (за счет двух проходов).

Поэтому, следует в данной функции применить всего один метод - `some` (https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/some), который обнаружит нужный элемент максимум за один проход, остановившись, если получится найти его раньше и вернет `boolean` значение

2022-09-17 13:35 UTC, randomroot commented on src/services/reducers/index.js
> +        case GET_INFO_CHOSEN_INGREDIENT: {
🟡 **Можно улучшить:**

Наименование данного типа на первый взгляд подразумевает получение какой-то информации, а в ходе его исполнение происходит именно установка значения в `store`, поэтому целесообразно заменить `GET_` на более подходящий по смысле `SET_`

2022-09-17 13:35 UTC, randomroot commented on src/services/reducers/index.js
> +                chosenIngredient: {}
🔴 **Нужно исправить:**

В вашей реализации `store` как раз и является объектом `chosenIngredient`, поэтому здесь на самом деле не происходит обнуление, а добавляется новый ключ с пустым значением. Проверить поведение ваших Redux сторов можно с помощью плагина в браузере, например в Chrome это `Redux DevTools` (см. https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd)

2022-09-17 13:35 UTC, randomroot commented on src/services/reducers/index.js
> +                    state.ingredientsConstructor.filter(item => item.type == 'bun').length ?
🟡 **Можно улучшить:**

1) Для поиска булки в массиве ингредиентов достаточно обнаружить самую первую из них, поэтому метод `filter` здесь можно заменить на `some`.

Аналогично ниже для ключа `ingredientsConstructor`

2) Данное выражение выполняется дважды в рамках одного `return`, поэтому его рекомендуется вынести в отдельную переменную и использовать далее её значение (тогда получится всего один поиск)

2022-09-17 13:35 UTC, randomroot commented on src/services/reducers/index.js
> +                        [action.item._id]: 1,
🔴 **Нужно исправить:**

Количество булок в рамках заказа равняется двум, а не одному :)

2022-09-17 13:35 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +    }, [ingredientsConstructor.length, ingredientsConstructor]);
🟡 **Можно улучшить:**

В качестве зависимостей достаточно оставить `ingredientsConstructor`, т.к. при изменении он будет приходит как новый массив из стора и `useEffect` сработает

2022-09-17 13:35 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +        if (ingredientsConstructor.length) setBunEl( ingredientsConstructor.find(el=>el.type==='bun') ? ingredientsConstructor.find(el=>el.type==='bun') : {});
🔴 **Нужно исправить:**

В рамках функции `setBunEl` происходит двойной поиск булки, данное выражение следует либо выделить в отдельную переменную, либо воспользоваться оператором ИЛИ `||`, который передаст второе значение, если отсутствует первое (см. https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/Logical_OR, обратите внимание на его особенности, если планируете использовать в дальнейшем)

2022-09-17 13:35 UTC, randomroot commented on src/services/reducers/index.js
> +            console.log(action.error);
🟡 **Можно улучшить:**

Ошибки лучше выводить с помощью метода `console.error`, чтобы можно было их удобно отфильтровать по типу сообщения в консоли

2022-09-17 13:35 UTC, randomroot commented on src/services/reducers/index.js
> +                {
🟡 **Можно улучшить:**

Т.к. в этом случае значение `counter` не изменяется можно безопасно вернуть его в исходном виде без дополнительного копирования

2022-09-17 15:42 UTC, Kartinkartin commented on src/components/burger-ingredients/burger-ingredients.jsx
> +        const currentTabRef = refs[positions.indexOf(Math.min.apply(null, positions))];
я так тут долго парилась из-за ерунды, что очень хочу оставить на память как открытку)

2022-09-17 16:00 UTC, Kartinkartin commented on src/components/burger-constructor/burger-constructor.jsx
> +    const [state, dispatchPrice] = useReducer(reducer, {price: 0});
я думала, но решила попрактиковаться, тоже хочу оставить)

2022-09-17 19:04 UTC, Kartinkartin commented on src/services/actions/index.js
> +        .then(res => checkRes(res))
Спасибо! Много классных замечаний.

2022-09-17 19:27 UTC, Kartinkartin commented on src/components/burger-constructor/burger-constructor.jsx
> +        if (ingredientsConstructor.length) setBunEl( ingredientsConstructor.find(el=>el.type==='bun') ? ingredientsConstructor.find(el=>el.type==='bun') : {});
Спасибо, голова моя дырявая)

2022-09-18 09:17 UTC, Kartinkartin commented on src/components/app/app.jsx
> +        <Modal title=' ' onClose={closePopup} number={orderNum}>
спасибо!

2022-09-18 09:19 UTC, Kartinkartin commented on src/components/layer/layer.jsx
> +export function Layer(props) {
Здесь я буду настаивать на своем наименовании, так как подразумеваю именно слой наполнения из начинок и соусов.

2022-09-19 09:15 UTC, randomroot requested changes
**Здравствуйте!**

Вы проделали большую работу по исправлению недостатков и добавлению улучшений в ваш проект!

Для успешной сдачи работы осталось внести еще несколько правок, отмеченных в ревью, связанных с переносом модальных окон и использованию хука внутри функции `return`.

Хорошего вам дня! 🐈 

_P.S. Следующее ревью будет проходить в рамках дополнительной итерации, согласованной с вашим куратором._

2022-09-19 09:15 UTC, randomroot commented on src/components/app/app.jsx
> +          <BurgerIngredients props={ [ openingDetails, setOpeningDetails, chosenItem, closePopup ] } />
🔴 **Нужно исправить:**

Классно, что воспользовались советом по переносу, однако следует перенести в том числе и всё что у вас указано в пропсах к компоненту: т.е. и хуки `openingDetails`, `chosenItem` и `closePopup`. Пусть всё лежит рядом, чтобы было визуально понятно, что к чему принадлежит. Плюс метод закрытия модалки сейчас обнуляет оба стора, хотя по факту изменения происходили только в одном, поэтому лучше такой код для каждой модалки делать свой узконаправленный.

_По текущему решению:_
1) Пропсы в объект следует передавать по отдельности, пропс `props` в данном случае излишен;
2) Не следует передавать пропсы как массив. Такой подход полезен для переменных хуков, чтобы разработчик мог переименовывать их на свой вкус, а в пропсах лучше использовать именно простой объект.

2022-09-19 09:15 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +                <div className={`${styles.constructor_element} pb-4`} >
🟡 **Можно улучшить:**

JSX элементы в рамках таких выражений рекомендуется оборачивать в круглые скобки (хорошее объяснение можно найти тут: https://medium.com/as-a-coder/why-you-should-wrap-your-jsx-with-parentheses-d7670293e45)

Дальше по коду аналогично.

_TLDR_: улучшает читабельность кода и позволяет избегать проблем с автоматической расстановки точек с запятой.

2022-09-19 09:15 UTC, randomroot commented on src/components/menu-category/menu-category.jsx
> +    const types = {
🟡 **Можно улучшить:**

Эту константу лучше вынести за пределы функции, чтобы она не пересоздавалась заново с каждым рендером :)

2022-09-19 09:15 UTC, randomroot commented on src/components/menu-category/menu-category.jsx
> +        <h2 ref={refer} className={`${styles.title} pt-10 pb-6 text text_type_main-medium`}>{types[type]}</h2>
🟡 **Можно улучшить:**

Следует поправить форматирование кода (отступы) для соблюдения визуальной иерархии компонентов

2022-09-19 09:15 UTC, randomroot commented on src/components/menu-category/menu-category.jsx
> +                useMemo(() => {return cards.filter(prod => prod.type === type)
🔴 **Нужно исправить:**

При использовании хука не следует использовать внутри таких конструкций, следует вынести `useMemo` в отдельную константу. 

Также обратите внимание на то, что метод `onClick` в этом случае также необходимо внести в массив зависимостей, по причине того, что он приходит из пропсов и может меняться. Чтобы избежать этого, можно в рамках `useMemo` вычислять именно отфильтрованный массив, а функцию `map` применять уже в рамках `return` здесь над результатом работы хука, тогда onClick будет в актуальном состоянии :)

2022-09-19 09:15 UTC, randomroot commented on src/components/menu-category/menu-category.jsx
> +    onClick: PropTypes.func
🟡 **Можно улучшить:**

Параметр является обязательным?

2022-09-19 09:15 UTC, randomroot commented on src/components/layer-element/layer-element.jsx
> +    const { prod, index, handleDelete, handleDrag, handleDrop } = props;
🟡 **Можно улучшить:**

Декомпозицию можно перенести на место `props` выше: `LayerElement({...})`

2022-09-19 09:15 UTC, randomroot commented on src/services/actions/index.js
> +function checkRes(res) {
🟡 **Можно улучшить:**

Идея комментария в предыдущем ревью заключалась в том, чтобы данная функция осталась в рамках `api.js`, но при этом её вызов был именно там, чтобы не выносить функцию проверки во внешний мир :)

2022-09-19 09:15 UTC, randomroot commented on src/services/actions/index.js
> +    const orderListId = orderList.map(item => item._id).concat(orderList[0]._id);
🟡 **Можно улучшить:**

Функция `concat` создаст новый массив для добавления одного элемента. Целесообразно заменить её на отдельный вызов `push`, чтобы не использовать дополнительную память

2022-09-19 09:15 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +                                    prod={item} index={index}
🟡 **Можно улучшить:**

Пропс `index` следует переместить на отдельную строку

2022-09-19 09:15 UTC, randomroot commented on src/services/reducers/index.js
> +            const currentBun = state.ingredientsConstructor.filter(item => item.type === 'bun')[0];
🟡 **Можно улучшить:**

1) Функцию `filter` в данном случае можно заменить на `find`, т.к. нас интересует любая из булок в массиве конструктора :)

2) Обратите внимание, что значение данной переменной используется только в момент когда `hasBun === true`, поэтому в обратном случае действие вычисление будет произведено. Лучше вызывать его при необходимости

2022-09-19 09:15 UTC, randomroot commented on src/services/reducers/index.js
> +            return { }
🟡 **Можно улучшить:**

Т.к. происходит сброс состояния стейта, то имеет смысл возвращать именно начальное значение, чтобы случайно не упустить какой-нибудь ключ, который добавится позже - `initialState.order`

2022-09-19 09:15 UTC, randomroot commented on src/services/actions/index.js
>  export const postOrder = (orderList) => {
🟡 **Можно улучшить:**

При успешном выполнении запроса целесообразно сбрасывать состояния конструктора, т.к. следующий заказ скорее всего будет из других ингредиентов :)

2022-09-19 17:45 UTC, Kartinkartin commented on src/components/menu-category/menu-category.jsx
> +    onClick: PropTypes.func
пардон, я утяль Т.Т

2022-09-19 20:27 UTC, randomroot approved these changes
🟢 **Работа принята!**

Поздравляю вас с успешным завершением этапа, вы проделали большую работу, научились новому и смогли улучшить качество и функциональность вашего кода. Особо отмечу ваш позитивный подход к результатам ревью и большое желание развиваться 👍 

По результатам финального ревью все необходимые исправления были оперативно внесены, улучшения учтены, замечаний к работе более не имеется.

**Успехов вам в дальнейшем обучении и хорошего дня!** 🐈 

<img src="https://media1.giphy.com/media/bt8FwKXiNKRkQ/200.webp?cid=ecf05e472obyq28m88f7lqvsr8hwr3d2rfr7fn0vugrrfku9&rid=200.webp&ct=g" />

2022-09-19 20:27 UTC, randomroot commented on src/components/burger-ingredients/burger-ingredients.jsx
> +                (<Modal title='Детали заказа' onClose={closePopup} element={chosenItem}>
🟡 **Можно улучшить:**

Обратите внимание на пропсы модального окна здесь и в конструкторе, здесь затесался диверсант, которого нет в `PropTypes` компонента `Modal` :)

2022-09-23 17:25 UTC, Kartinkartin commented on src/components/burger-ingredients/burger-ingredients.jsx
> +        setCurrent(currentSection === 'Булки' ? 'bun' :
Спасибо!!!! T.T

2022-09-24 18:49 UTC, merged